[package]
name = "music-player"
version = "0.1.0"
edition = "2024"

[dependencies]
evdev = { version = "0.13.2", optional = true }
image = { version = "0.25", default-features = false, features = ["jpeg"] }
libc = { version = "0.2.189", optional = true }
lofty = "0.25.2"
minifb = { version = "0.28.0", optional = true }
mpd = { git = "https://github.com/hardfau1t/rust-mpd", branch = "fix/83", version = "0.1.0" }

[build-dependencies]
fontdue = "0.9"
resvg = "0.45"
serde = { version = "1", features = ["derive"] }
tiny-skia = "0.11"
toml = "0.9"
ureq = "3"
usvg = "0.45"

[features]
default = ["desktop"]
debug = []
desktop = ["dep:minifb"]
raspberry = ["dep:evdev", "dep:libc"]
